export const SAVE_RESULTS = "SAVE_RESULTS";

export const LOAD_MODULES = "LOAD_MODULES";

export const LOAD_RESULTS = "LOAD_RESULTS";

export const LOAD_DEPARTMENTS = "LOAD_DEPARTMENTS";

export const LOAD_STAFF = "LOAD_STAFF";

export const LOAD_STUDENTS = "LOAD_STUDENTS";

export const REGISTER_STAFF = "REGISTER_STAFF";

export const REGISTER_STUDENT = "REGISTER_STUDENT";

export const LOAD_PROGRAMS = "LOAD_PROGRAM";
